### ISSUE TITLE
识别试题出来的都是乱码，大佬有没解决方案

### ISSUE THREAD

**Issue by Luffys6** [wangtaoT/AndroidOCR#12]

**Comment by wangtaoT** [comment]
这个应该是字典库的问题了！

**Comment by Luffys6** [comment]
> 这个应该是字典库的问题了！

有没办法更新下字典库

**Comment by wangtaoT** [comment]
已更新一个字典库，识别准确度会稍稍高一点！如果需要更高的准确度可能要自己训练！

Luffys6 <notifications@github.com> 于2019年10月15日周二 上午9:15写道：
